### PR TITLE
Remove unnecessary return statements from scala

### PR DESCRIPTION
**Pull request by javadba**
In scala it is not idiomatic to include "return" statements. This is a trivial cleanup.

### CODE REVIEW

**Comment by javadba** [comment]
Please merge/commit  this PR  AFTER #69. Why? #69 has a forward/reverse commit on this same code.

**Comment by javadba** [comment]
Hi,
    It appears this has not yet been applied to the javacpp+dataframes
branch?  Let's just not lose track of it ;)

2016-02-16 16:45 GMT-08:00 Robert Nishihara <notifications@github.com>:

**Comment by robertnishihara** [comment]
It appears to not have been applied to the master branch either. I merged #69 and that automatically merged this one as well (I never explicitly merged this PR).

**Comment by javadba** [comment]
Looks good. Thanks!


2016-02-16 23:01 GMT-08:00 Robert Nishihara <notifications@github.com>:

**Comment by robertnishihara** [comment]
Great, I think I just fixed it with `git cherry-pick`.

**Comment by javadba** [comment]
yes that did the trick.

2016-02-16 23:13 GMT-08:00 Robert Nishihara <notifications@github.com>:

**Pull request merged**
