### PR TITLE
Adding more details to steps for ImageNet App in Readme

### PR DESCRIPTION
**Pull request by rahulbhalerao001**

### CODE REVIEW

**Comment by robertnishihara** [comment]
Looks good! To make it a little simpler, can you replace steps 2 and 3 with a single step that says something like "Put the training and test data on S3 (see instructions in this issue)." And then renumber the subsequent steps appropriately.

**Comment by rahulbhalerao001** [comment]
Ok, I have simplified the instructions and renumbered the subsequent steps.

**Comment by robertnishihara** [comment]
Looks excellent! Can you squash those commits together, and then I'll merge it! http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by rahulbhalerao001** [comment]
I have squashed the commits together.
Thank you for the link with the information.

**Comment by robertnishihara** [comment]
Thanks a lot!

**Comment by robertnishihara** [comment]
Addresses #59.

**Pull request merged**
